--
-- Version: Each entry records results from a blood lab. Supports Azure SQL Server.
-- URL: http://ostlog.org/schema/Blood_log.json
--
CREATE TABLE [dbo].[Blood log]
(
	[id] INT IDENTITY (1,1) NOT NULL,
	[meta_id] INT NULL,
	[calendar_date_id] INT DEFAULT CONVERT (char(8), GETDATE(), 112) NOT NULL,
	[timestamp] TIME(0) NOT NULL,
	[location_id] INT NULL,
	[person_id] INT NOT NULL,
	[blood_group] NVARCHAR(3),
	[white_blood_cells_k_uL] FLOAT NULL,
	[red_blood_cells_M_uL] FLOAT NULL,
	[hemoglobin_g_dL] FLOAT NULL,
	[hematocrit_%] FLOAT NULL, 
	[mcv_fL] FLOAT NULL, 
	[mch_pg] FLOAT NULL, 
	[mchc_g_dL] FLOAT NULL, 
	[mpv_fL] FLOAT NULL, 
	[rdw_%] FLOAT NULL, 
	[platelet_k_uL] FLOAT NULL, 
	[neutrophils_%] FLOAT NULL, 
	[neutrophils_cells_k_uL] FLOAT NULL, 
	[eosinophils_%] FLOAT NULL, 
	[eosinophils_cells_k_uL] FLOAT NULL, 
	[basophils_%] FLOAT NULL, 
	[basophils_cells_k_uL] FLOAT NULL, 
	[lymphocytes_%] FLOAT NULL, 
	[lymphocytes_cells_k_uL] FLOAT NULL, 
	[monocytes_%] FLOAT NULL, 
	[monocytes_cells_k_uL] FLOAT NULL, 
	[erythroblasts_NRBC_%] FLOAT NULL,
	[erythroblasts_NRBC_k_uL] FLOAT NULL,
	[ferritin_ug_L] FLOAT NULL, 
	[sideremia_ug_dL] FLOAT NULL, 
	[creatinine_mg_dL] FLOAT NULL,
	[transferrin_mg_dL] FLOAT NULL,
	[transferrin_saturation_%] FLOAT NULL,
	[eGFR_mL_min] FLOAT NULL,
	[albumin_g_dL] FLOAT NULL, 
	[bile_acids_umol_L] FLOAT NULL, 
	[glucose_mg_dL] FLOAT NULL,
	[uricacid_mg_dL] FLOAT NULL, 
	[triglycerides_mg_dL] FLOAT NULL, 
	[cholesterol_total_mg_dL] FLOAT NULL,
	[cholesterol_hdl_mg_dL] FLOAT NULL, 
	[cholesterol_ldl_mg_dL] FLOAT NULL, 
	[ast_u_L] FLOAT NULL, 
	[alt_u_L] FLOAT NULL, 
	[ggt_u_L] FLOAT NULL, 
	[bilirubin_total_mg_dL] FLOAT NULL,
	[bilirubin_direct_mg_dL] FLOAT NULL,
	[bilirubin_indirect_mg_dL] FLOAT NULL,
	[ldh_uL_L] FLOAT NULL,	
	[toxoplasma_IgG_u_mL] FLOAT NULL, 
	[toxoplasma_IgM_u_mL] FLOAT NULL, 
	[tsh_uu_mL] FLOAT NULL,
	[t3_pmol_L] FLOAT NULL, 
	[t4_pmol_L] FLOAT NULL, 
	[potassium_meq_L] FLOAT NULL, 
	[sodium_meq_L] FLOAT NULL, 
	[calcium_meq_L] FLOAT NULL, 
	[beta_hcg_mu_mL] FLOAT NULL, 
	[crp_mg_L] FLOAT NULL, 
	[alp_u_L] FLOAT NULL,
	[psa_ng_mL] FLOAT NULL, 
	[psa_free_ng_mL] FLOAT NULL, 
	[esr_mm_hr] FLOAT NULL, 
	[urea_mg_dL] FLOAT NULL, 
	[hemolysis_index_md_dL] FLOAT NULL,
	[icterus_index_md_dL] FLOAT NULL,
	[lipemic index_md_dL] FLOAT NULL,
	[exam_results_url] NVARCHAR(512) NULL, 
	[remarks] NVARCHAR(2056) NULL,
	CONSTRAINT [PK_Blood log] PRIMARY KEY CLUSTERED ([id] ASC),
	CONSTRAINT [FK_Blood log-Calendar_date] FOREIGN KEY ([calendar_date_id]) REFERENCES [dbo].[Calendar dates] ([date_id]),
	CONSTRAINT [FK_Blood log-Location] FOREIGN KEY ([location_id]) REFERENCES [dbo].[Location] ([location_id]),
	CONSTRAINT [FK_Blood log-People] FOREIGN KEY ([person_id]) REFERENCES [dbo].[People] ([id]),
	CONSTRAINT [FK_Blood log-Meta log] FOREIGN KEY ([meta_id]) REFERENCES [dbo].[Meta log] ([id]),
	CHECK ([blood_group]='A+' OR [blood_group]='A-' OR [blood_group]='B+' OR [blood_group]='B-' OR [blood_group]='O+' OR [blood_group]='O-' OR [blood_group]='AB+' OR [blood_group]='AB-')
)
